### ISSUE TITLE
Feature request: disable question types

### ISSUE THREAD

**Issue by Teqa** [andrewtelnov/survey.js.editor#4]
It would be nice if we can disable certain question  types. 
Some questions  are confusing to an end user, like the HTML question. 
We would like these disabled. Possible to make a setting for this?

**Comment by andrewtelnov** [comment]
I have added the options parameter to the editor constructor. Right now it has only one property: questionTypes: Array<string>; Here is the example from Unit Test.
`var editor = new SurveyEditor.SurveyEditor(null, { questionTypes: ["text", "dropdown", "unknown"]});`
`assert.equal(editor.questionTypes.length, 2, "Only two types from three are accepted");`

Thank you,
Andrew
